services:
  web-app:
    container_name: web-app
    build:
      context: ./Docker
    stop_signal: SIGINT
    ports:
      - '8080:8080'
    environment:
      - PASSWORD=a46a5b2a871859c8e2d63d2f8c666807
    volumes:
      - ./data:/web-app/instance
